language: haxe

matrix:
  include:
    - os: osx
      osx_image: xcode9.3

# Get and install nightly hxcpp since 3.4.0 haxelib release is broken for recent iOS
before_install:
  - wget http://nmehost.com/releases/hxcpp/hxcpp-3.4.214.zip
  - haxelib install hxcpp-3.4.214.zip

# Install dependencies
install:
  - haxelib install lime
  - haxelib list

# Build the haxelib ndlls
script:
  - pushd project
  - chmod +x rebuild_ndlls.sh
  - ./rebuild_ndlls.sh
  - popd